# Generated by Django 3.2 on 2022-03-21 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthworker',
            name='attached_facility',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthworker',
            name='catchment_of_population_of_flcf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthworker',
            name='cnic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthworker',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthworker',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthworker',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthworker',
            name='population_registered_by_lhws',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthworker',
            name='tehsil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthworker',
            name='union_council',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthworker',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
