# Generated by Django 3.2 on 2022-03-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0003_alter_healthworker_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='healthworker',
            options={'permissions': (('can_view_healthwoker', 'Users Can view Health Worker Table'),)},
        ),
    ]
