# Generated by Django 3.2 on 2022-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0005_alter_healthworker_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthworker',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='healthworker/thumbnail/%Y/%m/%d/'),
        ),
    ]
