# Generated by Django 3.2 on 2022-03-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0007_healthworker_father_or_husband_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
