# Generated by Django 3.2 on 2022-03-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthworker',
            name='thumbnail',
            field=models.ImageField(blank=True, default='uploads/profile-img.jpg', null=True, upload_to='healthworker/thumbnail/%Y/%m/%d/'),
        ),
    ]
