# Generated by Django 3.2 on 2022-03-29 05:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_worker', '0009_alter_healthworker_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='administeredwithinjectablecontraceptive',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='alldeaths',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='anameia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='ari',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='aritimeravailable',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='aritimerfunction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='bloodpressureavailable',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='bloodpressurefunction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='canal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='clientsreferred',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='cocusers',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='condomusers',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='contraceptiveusers',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='datesubmmitted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='report',
            name='deathmorethanoneweek',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='deathsofchildren',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='deliveredbyskillattendants',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='diarrhoea',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_worker.district'),
        ),
        migrations.AddField(
            model_name='report',
            name='ecpusers',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='eligiblecouples',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='eyeinfection',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='fever',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='fistulacases',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='flush',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='followupcases',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='followupcasesforfamilyplanning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='handpump',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='heatlhboardavailable',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='helathboardfunction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='hepatitas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='householdregisteredbyhw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='householdusingiodine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='infantsdeaths',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='injuries',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='ironsuppliedpregnantwomen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='isheathcommittesformulated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='iswomensupportgroupformulated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='iucdclient',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='kitbagavailability',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='kitbagfucntional',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='lessthanfiveyearchildren',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='lessthanfiveyearchildrengmdone',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='lessthanfiveyearchildrenlowweight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='lessthanfiveyearchildrenprovidedsachet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='livebirths',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='malaria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='malnutritionchildren',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='maternaldeaths',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='maucforchildrenavailable',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='maucforchildrenfunction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='maucformotheravailable',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='maucformotherfunction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='misoprostol',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='modernmethodusers',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='newfamilyplanningclients',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='newnataldeaths',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='noofabortions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='noofhealthcommitteemeeting',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='noofhealtheducationsessionsheld',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='nooflowbirthweighted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='noofnewbirthstartedbreastfeeding',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='noofnewbornappliedchx',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='noofnewbornimmunestarted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='noofnewbornsweighted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='noofpregnantandbreastfeddingwomen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='openfields',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='oralpillusers',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='otheravailable',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='otherdiseases',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='otherdrinkingsource',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='otherfunction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='othermoderncontraceptiveusers',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='pit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='postnatalcasevisited',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='referalcasestohealthfacility',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='scabies',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='scissorsavailable',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='scissorsfunction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='sixmontholdchildren',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='sixmontholdchildrenhavingbreastfeed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='sixtofiveninechildrenhavingmaucdone',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='sixtofiveninemalnutritionchildren',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='sixtofiveninemonthchildren',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='stethoscopeavailable',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='stethoscopefunctional',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='stillbirths',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='suppliedwithcondoms',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='suppliedwithoral',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='surgicalclient',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='tap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='tbcases',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='thermometeravailable',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='thermometerfunction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='threemonthinjection',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='torchavailable',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='torchfunction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='totalhouseholdwithdrinkingwatersource',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='totalofdeliveries',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='totalpregnantwomen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='totalpregnantwomenvisited',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='tractinfection',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='traditionalmethodusers',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='twelvetotwentythreechildrenfullyimmunized',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='twelvetotwentythreemonthchildren',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='twomonthinjectiion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='visistsbyadc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='visistsbydco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='visistsbylhs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='visitsbyfpo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='visitsbyppiu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='weighingmachineavailability',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='weighingmachinefunction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='well',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='womendeliveredancvisists',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='womendeliveredtabprovided',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='womendeliveredwithttcompleted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='report',
            name='worminfection',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
