# Generated by Django 3.2 on 2022-03-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0012_auto_20220330_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='misoprostol',
            new_name='visitsbyadc',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='visistsbyadc',
            new_name='visitsbydco',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='visistsbydco',
            new_name='visitsbylhs',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='visistsbylhs',
            new_name='womendeliveredancvisits',
        ),
        migrations.RemoveField(
            model_name='report',
            name='womendeliveredancvisists',
        ),
    ]
