# Generated by Django 3.2 on 2022-03-30 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0013_auto_20220330_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='deliveredbyskillattendants',
            new_name='deliveredbyskilledattendants',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='twomonthinjectiion',
            new_name='twomonthinjection',
        ),
        migrations.RemoveField(
            model_name='report',
            name='datesubmmitted',
        ),
        migrations.AddField(
            model_name='report',
            name='datesubmitted',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
