# Generated by Django 3.2 on 2022-03-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0014_auto_20220330_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='otherfunction',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
