# Generated by Django 3.2 on 2022-03-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0015_alter_report_otherfunction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='heatlhboardavailable',
            new_name='healtboardfunction',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='helathboardfunction',
            new_name='healthboardavailable',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='kitbagfucntional',
            new_name='kitbagfunctional',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='stethoscopefunctional',
            new_name='stethoscopefunction',
        ),
    ]
