# Generated by Django 3.2 on 2022-04-04 15:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_worker', '0016_auto_20220330_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthworker',
            name='attached_facility',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='catchment_of_population_of_flcf',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='cnic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='population_registered_by_lhws',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='tehsil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='thumbnail',
            field=models.ImageField(default='uploads/profile-img.jpg', null=True, upload_to='healthworker/thumbnail/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='union_council',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='datesubmitted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='report',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_worker.district'),
        ),
        migrations.AlterField(
            model_name='report',
            name='isheathcommittesformulated',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='iswomensupportgroupformulated',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
