# Generated by Django 3.2 on 2022-04-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0017_auto_20220404_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthworker',
            name='father_or_husband_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='aritimeravailable',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='aritimerfunction',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='bloodpressureavailable',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='bloodpressurefunction',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='healtboardfunction',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='healthboardavailable',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='kitbagavailability',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='kitbagfunctional',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='maucforchildrenavailable',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='maucforchildrenfunction',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='maucformotheravailable',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='maucformotherfunction',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='otheravailable',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='otherfunction',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=55),
        ),
        migrations.AlterField(
            model_name='report',
            name='scissorsavailable',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='scissorsfunction',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='stethoscopeavailable',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='stethoscopefunction',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='thermometeravailable',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='thermometerfunction',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='torchavailable',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='torchfunction',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='weighingmachineavailability',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='weighingmachinefunction',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non Functional', 'Non Functional')], max_length=50),
        ),
    ]
