# Generated by Django 3.2 on 2022-04-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0018_auto_20220405_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='isheathcommittesformulated',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='iswomensupportgroupformulated',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=50),
        ),
    ]
