# Generated by Django 3.2 on 2022-05-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0020_auto_20220410_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthworker',
            name='dateofbirth',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='thumbnail',
            field=models.ImageField(blank=True, default='profile-img.jpg', null=True, upload_to='healthworker/thumbnail/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='isheathcommittesformulated',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='iswomensupportgroupformulated',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=50),
        ),
    ]
