# Generated by Django 3.2 on 2022-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0022_alter_healthworker_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthworker',
            name='age',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
