# Generated by Django 3.2 on 2022-05-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_worker', '0025_auto_20220531_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthworker',
            name='isRetired',
            field=models.BooleanField(null=True),
        ),
    ]
